### ISSUE TITLE
passing data from this.$vdialog.open

### ISSUE THREAD

**Issue by MrXploder** [derushio/instant-vuetify-overlays#1]
hi!, thnx for this incredible plugin.

I'm using the method this.$vdialog.open to open "dialogs" but I need to pass some data to it. It is posible with your library?

thnx in advance.

**Comment by MrXploder** [comment]
searching in your src/ folder I just realized that you can pass "propsData" object which key is the name of the prop, works perfect btw! thnx again!

**Comment by derushio** [comment]
Thank you for using the plugin.
Plugins seem to fit your mind.
If there is no problem, please close the issue.
😉
