### ISSUE TITLE
TypeError: r.a.compile is not a function

### ISSUE THREAD

**Issue by MrXploder** [derushio/instant-vuetify-overlays#2]
Hi!, here I'm again.

This time I receive this error when I try to do "this.$vdialog.alert('Hello');"

The full error es this:
```
Uncaught (in promise) TypeError: r.a.compile is not a function
    at vendors.app.js:2597
    at new Promise (<anonymous>)
    at VueComponent.open (vendors.app.js:2597)
    at VueComponent.alert (vendors.app.js:2597)
    at index.js:669
```

It happens when I open my custom component named "SendNotification.vue" with => 
```
import SendNotificationDialog from "~/dialogs/SendNotification";

method(){
const dialog = this.$vdialog.open({
      component: SendNotificationDialog,
      needCard: true,
      propsData: { items: this.DevicesSelected },
      width: 700
    });
}
```

In the "SendNotificationDialog" component when my promise resolves I call => 

```
onSend() {
    this.$messageService
      .notification(this.items)
      .then(() => {
        this.$vdialog.alert('Hello');
        this.$emit("ok");
      })
      .catch(() => this.$emit("cancel"));
  }
```

The dialogs closes but I receive the console error described above. Any help would be apreciated

**Comment by derushio** [comment]
okey, I developed the plugin on vue-property-decorator environment.
I'll try to develop on same your environment.

**Comment by MrXploder** [comment]
I'm using "nuxt-property-decorator" which seems to be a wrapper around "Vue-class-components" 
https://github.com/nuxt-community/nuxt-property-decorator

**Comment by derushio** [comment]
https://vuejs.org/v2/api/#Vue-compile

compile function not included on SSR.
Do you know import Vue for Brower Rendering in '.vue' file on nuxt?

**Comment by derushio** [comment]
i will try it
https://medium.com/haiiro-io/compile-markdown-as-vue-template-on-nuxt-js-1c606c15731c

**Comment by MrXploder** [comment]
I finally manage to get "instant-vuetify-overlays" working with my current nuxtjs setup.

I made it making all "import vue from "vue"" to import the included vue-compiler.

here is my nuxt.config.json which end up doing the "magic" :D

```
{
  build: {
    extend(config, ctx){
      config.resolve.alias["vue$"] = "vue/dist/vue.esm.js";
    }
  }
}
```
